name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix flake check -L
